### ISSUE TITLE
Error running standalone version 

### ISSUE THREAD

**Issue by MishaSavchenko** [ihmcrobotics/valkyrie#2]
When running through the instructions for installing the standalone version I get the following error:
```
msavchen@js-er-mizu:~$ ValkyrieObstacleCourseSCS2
Jan 09, 2024 2:47:00 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5a6d67c3'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at us.ihmc.javafx.JavaFXMissingTools.startup(JavaFXMissingTools.java:23)
	at us.ihmc.avatar.simulationStarter.DRCSimulationTools.showSelectorWithStartingLocation(DRCSimulationTools.java:106)
	at us.ihmc.avatar.simulationStarter.AvatarSimulationToolsSCS2.setupSimulationEnvironmentWithGraphicSelector(AvatarSimulationToolsSCS2.java:44)
	at us.ihmc.valkyrie.ValkyrieObstacleCourseNoUISCS2.<init>(ValkyrieObstacleCourseNoUISCS2.java:22)
	at us.ihmc.valkyrie.ValkyrieObstacleCourseNoUISCS2.main(ValkyrieObstacleCourseNoUISCS2.java:37)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:840)
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at us.ihmc.javafx.JavaFXMissingTools.startup(JavaFXMissingTools.java:23)
	at us.ihmc.avatar.simulationStarter.DRCSimulationTools.showSelectorWithStartingLocation(DRCSimulationTools.java:106)
	at us.ihmc.avatar.simulationStarter.AvatarSimulationToolsSCS2.setupSimulationEnvironmentWithGraphicSelector(AvatarSimulationToolsSCS2.java:44)
	at us.ihmc.valkyrie.ValkyrieObstacleCourseNoUISCS2.<init>(ValkyrieObstacleCourseNoUISCS2.java:22)
	at us.ihmc.valkyrie.ValkyrieObstacleCourseNoUISCS2.main(ValkyrieObstacleCourseNoUISCS2.java:37)
```

System Specs For Reference:
![image](https://github.com/ihmcrobotics/valkyrie/assets/17458981/cfc612e6-a7f7-44e1-bce6-8e878e47ee2e)

**Comment by SylvainBertrand** [comment]
Ok I think the debian is missing an explicit dependency. I was able to reproduce the error locally. I'll work on a fix tomorrow and let you know when it's ready to be tested!

**Comment by SylvainBertrand** [comment]
I just published a new release that should address this issue: https://github.com/ihmcrobotics/valkyrie/releases/tag/0.14.0-231219-1
I tested it on my Ubuntu laptop.
